project:
  type: website
  output-dir: docs
website:
  title: "Leo Souto's Personal Page"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: About
      - publications.qmd
    tools:
      - icon: github
        href: https://github.com/Leo-Souto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



