project:
  type: website
  output-dir: docs
website:
  title: "Leo Souto's Personal Page"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: About
      - publications.qmd
      - education.qmd
      - contact.qmd
    right:
      - text: "{{< iconify academicons google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=L_htG4AAAAAJ&hl=en
      - icon: github
        href: https://github.com/Leo-Souto


format:
  html:
    theme: pulse
    css: styles.css
    toc: true



